; PlatformIO Project Configuration File for Smart Obstacle Detection Auto-Braking Vehicle
; Target MCU: STM32F103C8T6 (Blue Pill)
; Upload Protocol: ST-Link V2

[platformio]
src_dir = firmware/Smart_Obstacle_4WD_Robot

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
monitor_speed = 9600
build_flags = 
    -D SERIAL_RX_BUFFER_SIZE=256
    -D SERIAL_TX_BUFFER_SIZE=256
